services:
  app:
    image: hykilpikonna/aquadx:latest
    ports:
      - "80:80"
      - "8443:8443"
      - "22345:22345"
    restart: on-failure:3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/main
      - SPRING_DATASOURCE_USERNAME=cat
      - SPRING_DATASOURCE_PASSWORD=meow
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
    depends_on:
      - db
    volumes:
      - ./config:/app/config
      - ./data:/app/data
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: meow
      MYSQL_DATABASE: main
      MYSQL_USER: cat
      MYSQL_PASSWORD: meow
    ports:
      - "127.0.0.1:3369:3306"
    volumes:
      - "./mariadb_data:/var/lib/mysql"
  aquanet:
      container_name: aquadx_aquanet
      build:
        context: .
        dockerfile: aquaNetDockerFile
      volumes:
        - ./AquaNet:/AquaNet
      ports:
        - "5173:5173"
      working_dir: "/AquaNet"
      command: "yarn dev --host"