# Build script credit to https://github.com/OpenIntelWireless/itlwm/blob/master/.github/workflows/main.yml
name: Nightly Build

on:
  push:
    branches: [master]
    paths: ['src/**']
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '10'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Artifact
        run: bash ./tools/build.sh

      - name: Delete previous nightly release
        run: |
          gh release delete --cleanup-tag --yes --repo $GITHUB_REPOSITORY nightly || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "build/release/ReleaseNotes.md"
          artifacts: "build/libs/aqua-nightly.jar,build/aqua-nightly.zip"
          tag: "nightly"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false

      - name: Mark release undraft
        run: |
          gh release edit nightly --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
